// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/asyncCalculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Undef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Undef) Reset() {
	*x = Undef{}
	mi := &file_proto_asyncCalculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Undef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Undef) ProtoMessage() {}

func (x *Undef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asyncCalculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Undef.ProtoReflect.Descriptor instead.
func (*Undef) Descriptor() ([]byte, []int) {
	return file_proto_asyncCalculator_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg1          float64                `protobuf:"fixed64,2,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float64                `protobuf:"fixed64,3,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationTime int32                  `protobuf:"varint,5,opt,name=OperationTime,proto3" json:"OperationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_asyncCalculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asyncCalculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_asyncCalculator_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *Task) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *Task) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Task) GetOperationTime() int32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_asyncCalculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asyncCalculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_asyncCalculator_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskResult) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_asyncCalculator_proto protoreflect.FileDescriptor

const file_proto_asyncCalculator_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/asyncCalculator.proto\x12\x05proto\"\a\n" +
	"\x05Undef\"\x82\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04arg1\x18\x02 \x01(\x01R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x03 \x01(\x01R\x04arg2\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12$\n" +
	"\rOperationTime\x18\x05 \x01(\x05R\rOperationTime\"N\n" +
	"\n" +
	"TaskResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2q\n" +
	"\x16AsyncCalculatorService\x12$\n" +
	"\aGetTask\x12\f.proto.Undef\x1a\v.proto.Task\x121\n" +
	"\x0ePostTaskResult\x12\x11.proto.TaskResult\x1a\f.proto.UndefB\rZ\vproto/protob\x06proto3"

var (
	file_proto_asyncCalculator_proto_rawDescOnce sync.Once
	file_proto_asyncCalculator_proto_rawDescData []byte
)

func file_proto_asyncCalculator_proto_rawDescGZIP() []byte {
	file_proto_asyncCalculator_proto_rawDescOnce.Do(func() {
		file_proto_asyncCalculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asyncCalculator_proto_rawDesc), len(file_proto_asyncCalculator_proto_rawDesc)))
	})
	return file_proto_asyncCalculator_proto_rawDescData
}

var file_proto_asyncCalculator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_asyncCalculator_proto_goTypes = []any{
	(*Undef)(nil),      // 0: proto.Undef
	(*Task)(nil),       // 1: proto.Task
	(*TaskResult)(nil), // 2: proto.TaskResult
}
var file_proto_asyncCalculator_proto_depIdxs = []int32{
	0, // 0: proto.AsyncCalculatorService.GetTask:input_type -> proto.Undef
	2, // 1: proto.AsyncCalculatorService.PostTaskResult:input_type -> proto.TaskResult
	1, // 2: proto.AsyncCalculatorService.GetTask:output_type -> proto.Task
	0, // 3: proto.AsyncCalculatorService.PostTaskResult:output_type -> proto.Undef
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_asyncCalculator_proto_init() }
func file_proto_asyncCalculator_proto_init() {
	if File_proto_asyncCalculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asyncCalculator_proto_rawDesc), len(file_proto_asyncCalculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asyncCalculator_proto_goTypes,
		DependencyIndexes: file_proto_asyncCalculator_proto_depIdxs,
		MessageInfos:      file_proto_asyncCalculator_proto_msgTypes,
	}.Build()
	File_proto_asyncCalculator_proto = out.File
	file_proto_asyncCalculator_proto_goTypes = nil
	file_proto_asyncCalculator_proto_depIdxs = nil
}
